services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - ${SERVER_PORT}:3000
    depends_on:
      - postgres

  postgres:
    image: postgres:15.2
    restart: always
    volumes:
      - postgres:/data/postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-test}
      POSTGRES_USER: ${DATABASE_USERNAME:-test}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-secret}
      PGDATA: /data/postgres

volumes:
  postgres:
