services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/app
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - ${SERVER_PORT}:3000
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.7
    restart: always
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD:-secret}
      MYSQL_DATABASE: ${DATABASE_NAME:-test}
      MYSQL_USER: ${DATABASE_USERNAME:-test}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:-secret}

volumes:
  data:
