services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - ${SERVER_PORT}:3000
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:6.0
    restart: always
    volumes:
      - mongo:/data/db
    ports:
      - 28017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME:-test}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD:-secret}
      MONGODB_DATABASE: ${DATABASE_NAME:-test}

  redis:
    image: redis:6
    restart: always
    volumes:
      - redis:/data
    ports:
      - 6379:6379

volumes:
  mongo:
  redis:
