services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - ${SERVER_PORT}:3000
    depends_on:
      - mariadb
      - redis

  mariadb:
    image: mariadb:10.7
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD:-secret}
      MYSQL_DATABASE: ${DATABASE_NAME:-test}
      MYSQL_USER: ${DATABASE_USERNAME:-test}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:-secret}

  redis:
    image: redis:6
    restart: always
    volumes:
      - redis:/data
    ports:
      - 6379:6379

volumes:
  mariadb:
  redis:
